name: Build

on:
  push:
    branches:
    - master
    - dev
    paths:
    - '.github/workflows/autobuild.yml'
    - 'assets/**'
    - 'binding/**'
    - 'linux/**'
    - 'macos/**'
    - 'shader/**'
    - 'src/**'
    - 'steamshim/**'
    - 'windows/**'
    - 'meson.build'
    - 'meson_options.txt'

  pull_request:
    branches:
    - master
    - dev
    paths:
    - '.github/workflows/autobuild.yml'
    - 'assets/**'
    - 'binding/**'
    - 'linux/**'
    - 'macos/**'
    - 'shader/**'
    - 'src/**'
    - 'steamshim/**'
    - 'windows/**'
    - 'meson.build'
    - 'meson_options.txt'

  workflow_dispatch:

jobs:
  build-windows:
    name: Windows (${{ matrix.sys }})
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - { sys: mingw32, env: i686, ruby-prefix: msvcrt }
        - { sys: mingw64, env: x86_64, ruby-prefix: x64-msvcrt }
        - { sys: ucrt64, env: ucrt-x86_64, ruby-prefix: x64-ucrt }

    steps:
      - name: Shorten commit SHA
        id: shorten-sha
        uses: benjlevesque/short-sha@v3.0
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2 (${{ matrix.sys }})
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          install: >-
            base-devel
            git
            vim
            ruby
            mingw-w64-${{ matrix.env }}-gcc
            mingw-w64-${{ matrix.env }}-autotools
            mingw-w64-${{ matrix.env }}-cmake
            mingw-w64-${{ matrix.env }}-meson

      - name: Dependencies cache
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: windows/build-${{ matrix.sys }}
          key: windows-${{ matrix.sys }}-${{ hashFiles('windows/Makefile') }}

      - name: Build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/windows
        shell: msys2 {0}
        run: make LTO=0

      - name: Build mkxp-z
        shell: msys2 {0}
        run: |
          source windows/vars.sh
          meson setup build --prefix="$GITHUB_WORKSPACE/build/artifact"
          meson compile -Cbuild
          meson install -Cbuild

      - name: Prepare artifact
        working-directory: ${{ github.workspace }}/build/artifact
        shell: msys2 {0}
        run: |
          strip ./*.exe
          strip ./*.dll
          strip ./rubylib/3.1.0/*/*.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z_Windows_${{ matrix.sys }}_${{ github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name }}_${{ steps.shorten-sha.outputs.sha }}
          path: build/artifact

  build-ubuntu-20:
    name: Ubuntu 20.04 (x86_64)
    runs-on: ubuntu-20.04

    steps:
      - name: Shorten commit SHA
        id: shorten-sha
        uses: benjlevesque/short-sha@v3.0
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install git vim wget patchelf ruby python3 python3-pip build-essential autoconf automake libtool pkg-config cmake bison libpulse-dev libasound2-dev libjack-dev portaudio19-dev libsamplerate0-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev
          sudo python3 -m pip install meson ninja

      # Required on Ubuntu 20.04 for libffi configuration
      - name: Install Autoconf 2.71
        working-directory: ${{ runner.temp }}
        run: |
          wget https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.xz
          tar -xf autoconf-2.71.tar.xz
          cd autoconf-2.71
          ./configure
          make
          sudo make install

      - name: Dependencies cache
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: linux/build-x86_64
          key: linux-x86_64-${{ hashFiles('linux/Makefile') }}

      - name: Build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/linux
        run: make LTO=0

      - name: Build mkxp-z
        run: |
          source linux/vars.sh
          meson build --prefix="$GITHUB_WORKSPACE/build/artifact"
          meson compile -Cbuild
          meson install -Cbuild

      - name: Prepare artifact
        working-directory: ${{ github.workspace }}/build/artifact
        run: |
          strip ./mkxp-z.x86_64
          strip ./lib64/libruby.so.3.1
          strip ./rubylib/3.1.0/*/*.so

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z_Ubuntu_20.04_x86-64_${{ github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name }}_${{ steps.shorten-sha.outputs.sha }}
          path: build/artifact

  build-macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: Shorten commit SHA
        id: shorten-sha
        uses: benjlevesque/short-sha@v3.0
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew packages
        working-directory: ${{ github.workspace }}/macos/dependencies
        run: brew bundle

      - name: Dependencies cache
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            macos/dependencies/build-x86_64
            macos/dependencies/build-arm64
            macos/dependencies/build-universal
          key: macos-${{ hashFiles('macos/dependencies/*.make', 'macos/dependencies/*.sh') }}

      - name: Build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/macos
        run: ./setup.command

      - name: Build mkxp-z
        working-directory: ${{ github.workspace }}/macos
        run: xcodebuild -project mkxp-z.xcodeproj -scheme "Universal" -configuration "Release" -derivedDataPath "$GITHUB_WORKSPACE/build"

      - name: Prepare artifact
        working-directory: ${{ github.workspace }}/build/Build/Products/Release
        run: |
          cp -v ../../../../assets/LICENSE.mkxp-z-with-https.txt Universal/
          ditto -Vkc --sequesterRsrc Universal mkxp-z.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkxp-z_macOS_${{ github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name }}_${{ steps.shorten-sha.outputs.sha }}
          path: build/Build/Products/Release/mkxp-z.zip
